title: Blog s3mPr1linux
description: "Blog For Hackers and not Hackers."
author:
  name: "s3mPr1linux"
  email: "s3mPr1linux@gmail.com"
  url: "https://s3mpr1linux.github.io/"
  twitter_username: jekyllrb
  github_username:  jekyll

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jeyll-avatar

# Custom variables
owner : "s3mPr1linux"
year : "2025"
